import java.io.*;

/**
 * Created by ma039102 on 5/12/2016.
 */
public class fileManipulation {

    public void createFile() {
        try {
            File file = new File("autogeneratedfile.txt");

            file.createNewFile();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void writeToFile(String toBeWritten) {
        try (Writer writer = new BufferedWriter(new OutputStreamWriter(new
                FileOutputStream("autogeneratedfile.txt")))){
            writer.write(toBeWritten);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public String getValues() {

        String line = null;
//        String toBeReturned = null;
        try {
            FileReader fileReader = new FileReader("autogeneratedfile.txt");

            BufferedReader bufferedReader = new BufferedReader(fileReader);

            while((line = bufferedReader.readLine()) != null) {
//                toBeReturned = bufferedReader.readLine();
                System.out.println(line);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return line;
    }
}
